<a href="https://colab.research.google.com/github/Konstantin-Larionov/ds_sb_2020_homework/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Part_1_HW_Write_our_own_library_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [1]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Writing lib.py


In [2]:
from lib import summ

In [3]:
summ(2,6)

8

Попробуем запустить через "терминал"

In [4]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [5]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


Overwriting lib.py


In [6]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [42]:
%%writefile my_math_lib.py
import numpy as np


def deg_to_rad(deg):
  rad = deg/57.3
  return rad

def rad_to_deg(rad):
  deg = rad*57.3
  return deg

def discriminant(a,b,c):
  D = b**2 - 4*a*c
  return D

def power_base_sum(a,b):
  string = str(a**b)
  result = 0
  for num in string:
    result += int(num)
  return result

def magic_square(n):
  A=np.zeros([n,n])
  for i in range(n):
        A[i][i]=(n-1)/2
        for k in range(n):
            if k<(n-1)/2:
                if i+k+1<n:
                    A[i][i+k+1]=k
                else:
                    A[i][i+k+1-n]=k
            else:
                if k==(n-1)/2:
                    pass
                else:
                    if k+i<n:
                        A[i][i+k]=k
                    else:
                        A[i][i+k-n]=k
  B=np.zeros([n,n])
  for i in range(n):   
    for k in range(n):
        B[i][k]=A[i][k]*n+A[i][n-1-k]+1
  return B

def mult_list(a):
  b=1
  for i in a:
    b *= i
  return b

def create_list():
  sqlist = [i**2 for i in range(1,31)]
  return print(sqlist)

Overwriting my_math_lib.py


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [44]:
from my_math_lib import discriminant, magic_square

In [47]:
D = discriminant(1,3,4)
magicsq5 = magic_square(5)
print(D)
print(magicsq5)

-7
[[15.  4.  7. 16. 23.]
 [24. 12.  1.  8. 20.]
 [17. 21. 13.  5.  9.]
 [ 6. 18. 25. 14.  2.]
 [ 3. 10. 19. 22. 11.]]


# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [48]:
#TODO
%%writefile my_math_lib.py
import numpy as np
import sys

a1 = float( sys.argv[1] ) 
b1 = float( sys.argv[2] ) 
c1 = float( sys.argv[3] )

def deg_to_rad(deg):
  rad = deg/57.3
  return rad

def rad_to_deg(rad):
  deg = rad*57.3
  return deg

def discriminant(a,b,c):
  D = b**2 - 4*a*c
  return D

def power_base_sum(a,b):
  string = str(a**b)
  result = 0
  for num in string:
    result += int(num)
  return result

def magic_square(n):
  A=np.zeros([n,n])
  for i in range(n):
        A[i][i]=(n-1)/2
        for k in range(n):
            if k<(n-1)/2:
                if i+k+1<n:
                    A[i][i+k+1]=k
                else:
                    A[i][i+k+1-n]=k
            else:
                if k==(n-1)/2:
                    pass
                else:
                    if k+i<n:
                        A[i][i+k]=k
                    else:
                        A[i][i+k-n]=k
  B=np.zeros([n,n])
  for i in range(n):   
    for k in range(n):
        B[i][k]=A[i][k]*n+A[i][n-1-k]+1
  return B

def mult_list(a):
  b=1
  for i in a:
    b *= i
  return b

def create_list():
  sqlist = [i**2 for i in range(1,31)]
  return print(sqlist)

if __name__ == "__main__":
    print(discriminant(a1, b1, c1))

Overwriting my_math_lib.py


In [50]:
# Пример вызова функции - Вы можете вызвать любую другую
!python3 my_math_lib.py 3 4 5 # Например если в __main__ вы указали def discriminant()

-44.0
