<a href="https://colab.research.google.com/github/Konstantin-Larionov/ds_sb_2020_homework/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22HW_7_lesson_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [ ]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [3]:
import numpy as np
#2
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1],[0,5]])
print(a+b)
print(np.dot(a,b))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


In [4]:
#3
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
print((3*A)-(2*B)+(4*C))

[[ 11  -5]
 [  9 -12]]


In [6]:
#4
A = np.array([[4,1],[5,-2],[2,3]])
print(np.dot(A,A.T))
print(np.dot(A.T,A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]



__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [9]:
#6
import math as mt
x = mt.pi
A = np.array([[mt.sin(x),-1*mt.cos(x)],[mt.cos(x),mt.sin(x)]])
print(f'а){np.linalg.det(A)}')

B = np.array([[8,4,6],[0,5,1],[0,0,9]])
print(f'б){np.linalg.det(B)}')

V = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(f'в){np.linalg.det(V)}')

а)1.0
б)360.00000000000006
в)0.0


In [ ]:
#7 для решения данного задания были использованы свойства определителей без вычислений в python

In [12]:
#8
A = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
print(f'Если определитель = 0, а он равен {np.linalg.det(A)}, значит матрица вырожденная')

Если определитель = 0, а он равен 0.0, значит матрица вырожденная


In [14]:
#9
A = np.array([[1,2,3],[1,1,1],[2,3,4]])
print(f'а){np.linalg.matrix_rank(A)}')

B = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
print(f'б){np.linalg.matrix_rank(B)}')

а)2
б)3


# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)